# File: .github/workflows/template-sync.yml

on:
  schedule:
  - cron:  "0 0 1 * *"
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v1.1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: elixir-europe-training/ELIXIR-TrP-LessonTemplate-MkDocs
          upstream_branch: main
